### ISSUE TITLE
Sound increment of 10

### ISSUE THREAD

**Issue by Duck999** [mcanterb/JRGSS#14] opened 2015-02-13 00:03 UTC
When changing the sound settings, there is a message that you can hold shift to have volume go up or down in increments of 10, but it still goes up and down 1 at a time when you hold shift.

**Comment by zslayton** [comment] 2015-02-13 00:21
Hi @Duck999, I believe this is a duplicate of issue #11, which was resolved earlier today. It should be functional in the next build.

**Comment by mcanterb** [comment] 2015-02-13 04:09
Closing for now

**Closed as completed by mcanterb** 2015-02-13 04:09 UTC
Labels: duplicate
